### ISSUE TITLE
race times page?

### ISSUE THREAD

**Issue by bonifarz** [shacknetisp/statsdb-interface#7]
It is cool that the maps page includes the best race times, but it looks a bit odd with all the empty fields of non-race maps.

Would it be possible to have a separate page with race maps only (i.e. anything played in race mode), and to list the best lap times there, maybe with an additional column for the endurance mutator? This mutator is not very popular atm, but that feature could change this. What do you think?

**Comment by shacknetisp** [comment]
http://play.redeclipse.net:28700/racemaps

**Comment by bonifarz** [comment]
Cool, thanks.

It's your choice whether you want to keep the times on the _maps_ page, either way is fine.
